#!/usr/bin/env sh
# Verify committed Skillshare targets against their repository sources.
#
# Skill targets are not committed (ADR-040). `.claude/skills/` and
# `.agents/skills/` are generated by `skillshare sync -p` on each machine, so
# there is no committed copy left to compare; the frontmatter that a target
# copy used to guard indirectly is checked at the source by check-frontmatter.sh.
#
# Agents and commands are still committed. Skillshare 0.20.x does not track
# files copied to those targets in a manifest, so `skillshare diff` reports
# every one of them as a local override. This check compares the actual files.

set -eu

SOURCE_AGENTS='.skillshare/agents'
SOURCE_COMMANDS='.skillshare/extras/commands'
CLAUDE_AGENTS='.claude/agents'
CLAUDE_COMMANDS='.claude/commands'
errors=''

fail() {
    errors="${errors}  - $1
"
}

# A target is a copy of its source, so the comparison allows exactly one
# difference: the line ending Git may have used on checkout.
compare_file() {
    source=$1
    target=$2
    label=$3

    if [ ! -f "$target" ]; then
        fail "${label}: missing target ${target}"
    elif ! git diff --no-index --ignore-cr-at-eol --exit-code -- "$source" "$target" >/dev/null 2>&1; then
        fail "${label}: ${source} and ${target} differ"
    fi
}

for agent_source in "$SOURCE_AGENTS"/*.md; do
    [ -f "$agent_source" ] || continue
    name=$(basename "$agent_source")
    compare_file "$agent_source" "$CLAUDE_AGENTS/$name" "agent ${name}"
done

for agent_target in "$CLAUDE_AGENTS"/*.md; do
    [ -f "$agent_target" ] || continue
    name=$(basename "$agent_target")
    if [ ! -f "$SOURCE_AGENTS/$name" ]; then
        fail "agent ${name}: target has no source"
    fi
done

for command_source in "$SOURCE_COMMANDS"/*; do
    [ -f "$command_source" ] || continue
    name=$(basename "$command_source")
    compare_file "$command_source" "$CLAUDE_COMMANDS/$name" "command ${name}"
done

for command_target in "$CLAUDE_COMMANDS"/*; do
    [ -f "$command_target" ] || continue
    name=$(basename "$command_target")
    if [ ! -f "$SOURCE_COMMANDS/$name" ]; then
        fail "command ${name}: target has no source"
    fi
done

if [ -n "$errors" ]; then
    printf 'Agent tooling is not synchronized:\n\n%s\n' "$errors" >&2
    printf 'Sync the targets from .skillshare/ and re-run the check:\n\n' >&2
    printf '  skillshare sync -p          # agents\n' >&2
    printf '  skillshare sync extras -p   # commands\n' >&2
    printf '  just check-agent-tools\n' >&2
    exit 1
fi

printf 'Agent tooling is synchronized.\n'
