<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ContractSurface.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Meetups.Contracts\Meetups.Contracts.csproj" />
  </ItemGroup>

</Project>
