<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka" Version="1.5.55" />
    <PackageReference Include="Akka.Persistence" Version="1.5.55" />
    <PackageReference Include="Akka.Persistence.Sql" Version="1.5.55.1" />
    <PackageReference Include="Akka.Persistence.Sql.Hosting" Version="1.5.55.1" />
    <PackageReference Include="Akka.Serialization.Hyperion" Version="1.5.55" />
    <PackageReference Include="Akka.Hosting" Version="1.5.55.1" />
    <PackageReference Include="Akka.DependencyInjection" Version="1.5.55" />
    <PackageReference Include="Akka.Persistence.Hosting" Version="1.5.55.1" />
    <PackageReference Include="Akka.Logger.Serilog" Version="1.5.25" />
    <PackageReference Include="linq2db" Version="5.4.1" />

    <PackageReference Include="Grpc.AspNetCore" Version="2.65.0" />
    <PackageReference Include="Google.Protobuf" Version="3.28.3" />
    <PackageReference Include="Grpc.Tools" Version="2.65.0" PrivateAssets="All" />

    <PackageReference Include="NATS.Client" Version="1.1.8" />

    <PackageReference Include="Serilog.AspNetCore" Version="8.0.2" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />

    <PackageReference Include="Npgsql" Version="8.0.5" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\..\..\contracts\proto\grpc\auction_service.proto" GrpcServices="Server" ProtoRoot="..\..\..\..\contracts\proto" />
    <Protobuf Include="..\..\..\..\contracts\proto\nats\commands\auction_commands.proto" GrpcServices="None" ProtoRoot="..\..\..\..\contracts\proto" />
    <Protobuf Include="..\..\..\..\contracts\proto\nats\events\auction_events.proto" GrpcServices="None" ProtoRoot="..\..\..\..\contracts\proto" />
    <Protobuf Include="..\..\..\..\contracts\proto\common\types.proto" GrpcServices="None" ProtoRoot="..\..\..\..\contracts\proto" />
  </ItemGroup>

</Project>

