application:
  host: "0.0.0.0"
  port: 8000
telegram:
  # Этот токен будет переопределен переменной окружения APP_TELEGRAM__TOKEN
  token: "placeholder_token"
nats:
  # Этот URL будет переопределен переменной окружения APP_NATS__URL
  url: "nats://127.0.0.1:4222"
apicurio:
  # Этот URL будет использоваться для автоматической регистрации схем (будущая функциональность)
  url: "http://apicurio-registry:8080"
auth:
  # Список Telegram ID администраторов
  # Может быть переопределен через APP_AUTH__ADMINS="123456789,987654321"
  admins: [364267879]
