[env]
RUST_BACKTRACE = "1"
RUST_LOG = "info,teloxide=info,telegram_gateway=debug"

[profile.dev]
opt-level = 1
debug = 2
incremental = true

[profile.release]
lto = "thin"
codegen-units = 1

[alias]
c = "check"

[build]
rustflags = ["-D", "warnings"]
